################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/Lapack/Scr/dbdsqr.c \
../src/Lapack/Scr/dgebak.c \
../src/Lapack/Scr/dgebal.c \
../src/Lapack/Scr/dgebd2.c \
../src/Lapack/Scr/dgebrd.c \
../src/Lapack/Scr/dgeev.c \
../src/Lapack/Scr/dgehd2.c \
../src/Lapack/Scr/dgehrd.c \
../src/Lapack/Scr/dgelq2.c \
../src/Lapack/Scr/dgelqf.c \
../src/Lapack/Scr/dgeqr2.c \
../src/Lapack/Scr/dgeqrf.c \
../src/Lapack/Scr/dgesv.c \
../src/Lapack/Scr/dgesvd.c \
../src/Lapack/Scr/dgetf2.c \
../src/Lapack/Scr/dgetrf.c \
../src/Lapack/Scr/dgetrs.c \
../src/Lapack/Scr/dhseqr.c \
../src/Lapack/Scr/disnan.c \
../src/Lapack/Scr/dlabad.c \
../src/Lapack/Scr/dlabrd.c \
../src/Lapack/Scr/dlacpy.c \
../src/Lapack/Scr/dladiv.c \
../src/Lapack/Scr/dlaexc.c \
../src/Lapack/Scr/dlahqr.c \
../src/Lapack/Scr/dlahr2.c \
../src/Lapack/Scr/dlaisnan.c \
../src/Lapack/Scr/dlaln2.c \
../src/Lapack/Scr/dlange.c \
../src/Lapack/Scr/dlanv2.c \
../src/Lapack/Scr/dlapy2.c \
../src/Lapack/Scr/dlaqr0.c \
../src/Lapack/Scr/dlaqr1.c \
../src/Lapack/Scr/dlaqr2.c \
../src/Lapack/Scr/dlaqr3.c \
../src/Lapack/Scr/dlaqr4.c \
../src/Lapack/Scr/dlaqr5.c \
../src/Lapack/Scr/dlarf.c \
../src/Lapack/Scr/dlarfb.c \
../src/Lapack/Scr/dlarfg.c \
../src/Lapack/Scr/dlarfp.c \
../src/Lapack/Scr/dlarft.c \
../src/Lapack/Scr/dlarfx.c \
../src/Lapack/Scr/dlartg.c \
../src/Lapack/Scr/dlas2.c \
../src/Lapack/Scr/dlascl.c \
../src/Lapack/Scr/dlaset.c \
../src/Lapack/Scr/dlasq1.c \
../src/Lapack/Scr/dlasq2.c \
../src/Lapack/Scr/dlasq3.c \
../src/Lapack/Scr/dlasq4.c \
../src/Lapack/Scr/dlasq5.c \
../src/Lapack/Scr/dlasq6.c \
../src/Lapack/Scr/dlasr.c \
../src/Lapack/Scr/dlasrt.c \
../src/Lapack/Scr/dlassq.c \
../src/Lapack/Scr/dlasv2.c \
../src/Lapack/Scr/dlaswp.c \
../src/Lapack/Scr/dlasy2.c \
../src/Lapack/Scr/dorg2r.c \
../src/Lapack/Scr/dorgbr.c \
../src/Lapack/Scr/dorghr.c \
../src/Lapack/Scr/dorgl2.c \
../src/Lapack/Scr/dorglq.c \
../src/Lapack/Scr/dorgqr.c \
../src/Lapack/Scr/dorm2r.c \
../src/Lapack/Scr/dormbr.c \
../src/Lapack/Scr/dormhr.c \
../src/Lapack/Scr/dorml2.c \
../src/Lapack/Scr/dormlq.c \
../src/Lapack/Scr/dormqr.c \
../src/Lapack/Scr/dtrevc.c \
../src/Lapack/Scr/dtrexc.c \
../src/Lapack/Scr/ieeeck.c \
../src/Lapack/Scr/iladlc.c \
../src/Lapack/Scr/iladlr.c \
../src/Lapack/Scr/ilaenv.c \
../src/Lapack/Scr/ilaslc.c \
../src/Lapack/Scr/ilaslr.c \
../src/Lapack/Scr/iparmq.c \
../src/Lapack/Scr/sgebak.c \
../src/Lapack/Scr/sgebal.c \
../src/Lapack/Scr/sgeev.c \
../src/Lapack/Scr/sgehd2.c \
../src/Lapack/Scr/sgehrd.c \
../src/Lapack/Scr/sgeqr2.c \
../src/Lapack/Scr/sgetf2.c \
../src/Lapack/Scr/sgetrf.c \
../src/Lapack/Scr/shseqr.c \
../src/Lapack/Scr/sisnan.c \
../src/Lapack/Scr/slabad.c \
../src/Lapack/Scr/slacpy.c \
../src/Lapack/Scr/sladiv.c \
../src/Lapack/Scr/slaexc.c \
../src/Lapack/Scr/slahqr.c \
../src/Lapack/Scr/slahr2.c \
../src/Lapack/Scr/slaisnan.c \
../src/Lapack/Scr/slaln2.c \
../src/Lapack/Scr/slange.c \
../src/Lapack/Scr/slanv2.c \
../src/Lapack/Scr/slapy2.c \
../src/Lapack/Scr/slaqr0.c \
../src/Lapack/Scr/slaqr1.c \
../src/Lapack/Scr/slaqr2.c \
../src/Lapack/Scr/slaqr3.c \
../src/Lapack/Scr/slaqr4.c \
../src/Lapack/Scr/slaqr5.c \
../src/Lapack/Scr/slarf.c \
../src/Lapack/Scr/slarfb.c \
../src/Lapack/Scr/slarfg.c \
../src/Lapack/Scr/slarfp.c \
../src/Lapack/Scr/slarft.c \
../src/Lapack/Scr/slarfx.c \
../src/Lapack/Scr/slartg.c \
../src/Lapack/Scr/slascl.c \
../src/Lapack/Scr/slaset.c \
../src/Lapack/Scr/slassq.c \
../src/Lapack/Scr/slaswp.c \
../src/Lapack/Scr/slasy2.c \
../src/Lapack/Scr/sorg2r.c \
../src/Lapack/Scr/sorghr.c \
../src/Lapack/Scr/sorgqr.c \
../src/Lapack/Scr/sorm2r.c \
../src/Lapack/Scr/sormhr.c \
../src/Lapack/Scr/sormqr.c \
../src/Lapack/Scr/strevc.c \
../src/Lapack/Scr/strexc.c 

OBJS += \
./src/Lapack/Scr/dbdsqr.o \
./src/Lapack/Scr/dgebak.o \
./src/Lapack/Scr/dgebal.o \
./src/Lapack/Scr/dgebd2.o \
./src/Lapack/Scr/dgebrd.o \
./src/Lapack/Scr/dgeev.o \
./src/Lapack/Scr/dgehd2.o \
./src/Lapack/Scr/dgehrd.o \
./src/Lapack/Scr/dgelq2.o \
./src/Lapack/Scr/dgelqf.o \
./src/Lapack/Scr/dgeqr2.o \
./src/Lapack/Scr/dgeqrf.o \
./src/Lapack/Scr/dgesv.o \
./src/Lapack/Scr/dgesvd.o \
./src/Lapack/Scr/dgetf2.o \
./src/Lapack/Scr/dgetrf.o \
./src/Lapack/Scr/dgetrs.o \
./src/Lapack/Scr/dhseqr.o \
./src/Lapack/Scr/disnan.o \
./src/Lapack/Scr/dlabad.o \
./src/Lapack/Scr/dlabrd.o \
./src/Lapack/Scr/dlacpy.o \
./src/Lapack/Scr/dladiv.o \
./src/Lapack/Scr/dlaexc.o \
./src/Lapack/Scr/dlahqr.o \
./src/Lapack/Scr/dlahr2.o \
./src/Lapack/Scr/dlaisnan.o \
./src/Lapack/Scr/dlaln2.o \
./src/Lapack/Scr/dlange.o \
./src/Lapack/Scr/dlanv2.o \
./src/Lapack/Scr/dlapy2.o \
./src/Lapack/Scr/dlaqr0.o \
./src/Lapack/Scr/dlaqr1.o \
./src/Lapack/Scr/dlaqr2.o \
./src/Lapack/Scr/dlaqr3.o \
./src/Lapack/Scr/dlaqr4.o \
./src/Lapack/Scr/dlaqr5.o \
./src/Lapack/Scr/dlarf.o \
./src/Lapack/Scr/dlarfb.o \
./src/Lapack/Scr/dlarfg.o \
./src/Lapack/Scr/dlarfp.o \
./src/Lapack/Scr/dlarft.o \
./src/Lapack/Scr/dlarfx.o \
./src/Lapack/Scr/dlartg.o \
./src/Lapack/Scr/dlas2.o \
./src/Lapack/Scr/dlascl.o \
./src/Lapack/Scr/dlaset.o \
./src/Lapack/Scr/dlasq1.o \
./src/Lapack/Scr/dlasq2.o \
./src/Lapack/Scr/dlasq3.o \
./src/Lapack/Scr/dlasq4.o \
./src/Lapack/Scr/dlasq5.o \
./src/Lapack/Scr/dlasq6.o \
./src/Lapack/Scr/dlasr.o \
./src/Lapack/Scr/dlasrt.o \
./src/Lapack/Scr/dlassq.o \
./src/Lapack/Scr/dlasv2.o \
./src/Lapack/Scr/dlaswp.o \
./src/Lapack/Scr/dlasy2.o \
./src/Lapack/Scr/dorg2r.o \
./src/Lapack/Scr/dorgbr.o \
./src/Lapack/Scr/dorghr.o \
./src/Lapack/Scr/dorgl2.o \
./src/Lapack/Scr/dorglq.o \
./src/Lapack/Scr/dorgqr.o \
./src/Lapack/Scr/dorm2r.o \
./src/Lapack/Scr/dormbr.o \
./src/Lapack/Scr/dormhr.o \
./src/Lapack/Scr/dorml2.o \
./src/Lapack/Scr/dormlq.o \
./src/Lapack/Scr/dormqr.o \
./src/Lapack/Scr/dtrevc.o \
./src/Lapack/Scr/dtrexc.o \
./src/Lapack/Scr/ieeeck.o \
./src/Lapack/Scr/iladlc.o \
./src/Lapack/Scr/iladlr.o \
./src/Lapack/Scr/ilaenv.o \
./src/Lapack/Scr/ilaslc.o \
./src/Lapack/Scr/ilaslr.o \
./src/Lapack/Scr/iparmq.o \
./src/Lapack/Scr/sgebak.o \
./src/Lapack/Scr/sgebal.o \
./src/Lapack/Scr/sgeev.o \
./src/Lapack/Scr/sgehd2.o \
./src/Lapack/Scr/sgehrd.o \
./src/Lapack/Scr/sgeqr2.o \
./src/Lapack/Scr/sgetf2.o \
./src/Lapack/Scr/sgetrf.o \
./src/Lapack/Scr/shseqr.o \
./src/Lapack/Scr/sisnan.o \
./src/Lapack/Scr/slabad.o \
./src/Lapack/Scr/slacpy.o \
./src/Lapack/Scr/sladiv.o \
./src/Lapack/Scr/slaexc.o \
./src/Lapack/Scr/slahqr.o \
./src/Lapack/Scr/slahr2.o \
./src/Lapack/Scr/slaisnan.o \
./src/Lapack/Scr/slaln2.o \
./src/Lapack/Scr/slange.o \
./src/Lapack/Scr/slanv2.o \
./src/Lapack/Scr/slapy2.o \
./src/Lapack/Scr/slaqr0.o \
./src/Lapack/Scr/slaqr1.o \
./src/Lapack/Scr/slaqr2.o \
./src/Lapack/Scr/slaqr3.o \
./src/Lapack/Scr/slaqr4.o \
./src/Lapack/Scr/slaqr5.o \
./src/Lapack/Scr/slarf.o \
./src/Lapack/Scr/slarfb.o \
./src/Lapack/Scr/slarfg.o \
./src/Lapack/Scr/slarfp.o \
./src/Lapack/Scr/slarft.o \
./src/Lapack/Scr/slarfx.o \
./src/Lapack/Scr/slartg.o \
./src/Lapack/Scr/slascl.o \
./src/Lapack/Scr/slaset.o \
./src/Lapack/Scr/slassq.o \
./src/Lapack/Scr/slaswp.o \
./src/Lapack/Scr/slasy2.o \
./src/Lapack/Scr/sorg2r.o \
./src/Lapack/Scr/sorghr.o \
./src/Lapack/Scr/sorgqr.o \
./src/Lapack/Scr/sorm2r.o \
./src/Lapack/Scr/sormhr.o \
./src/Lapack/Scr/sormqr.o \
./src/Lapack/Scr/strevc.o \
./src/Lapack/Scr/strexc.o 

C_DEPS += \
./src/Lapack/Scr/dbdsqr.d \
./src/Lapack/Scr/dgebak.d \
./src/Lapack/Scr/dgebal.d \
./src/Lapack/Scr/dgebd2.d \
./src/Lapack/Scr/dgebrd.d \
./src/Lapack/Scr/dgeev.d \
./src/Lapack/Scr/dgehd2.d \
./src/Lapack/Scr/dgehrd.d \
./src/Lapack/Scr/dgelq2.d \
./src/Lapack/Scr/dgelqf.d \
./src/Lapack/Scr/dgeqr2.d \
./src/Lapack/Scr/dgeqrf.d \
./src/Lapack/Scr/dgesv.d \
./src/Lapack/Scr/dgesvd.d \
./src/Lapack/Scr/dgetf2.d \
./src/Lapack/Scr/dgetrf.d \
./src/Lapack/Scr/dgetrs.d \
./src/Lapack/Scr/dhseqr.d \
./src/Lapack/Scr/disnan.d \
./src/Lapack/Scr/dlabad.d \
./src/Lapack/Scr/dlabrd.d \
./src/Lapack/Scr/dlacpy.d \
./src/Lapack/Scr/dladiv.d \
./src/Lapack/Scr/dlaexc.d \
./src/Lapack/Scr/dlahqr.d \
./src/Lapack/Scr/dlahr2.d \
./src/Lapack/Scr/dlaisnan.d \
./src/Lapack/Scr/dlaln2.d \
./src/Lapack/Scr/dlange.d \
./src/Lapack/Scr/dlanv2.d \
./src/Lapack/Scr/dlapy2.d \
./src/Lapack/Scr/dlaqr0.d \
./src/Lapack/Scr/dlaqr1.d \
./src/Lapack/Scr/dlaqr2.d \
./src/Lapack/Scr/dlaqr3.d \
./src/Lapack/Scr/dlaqr4.d \
./src/Lapack/Scr/dlaqr5.d \
./src/Lapack/Scr/dlarf.d \
./src/Lapack/Scr/dlarfb.d \
./src/Lapack/Scr/dlarfg.d \
./src/Lapack/Scr/dlarfp.d \
./src/Lapack/Scr/dlarft.d \
./src/Lapack/Scr/dlarfx.d \
./src/Lapack/Scr/dlartg.d \
./src/Lapack/Scr/dlas2.d \
./src/Lapack/Scr/dlascl.d \
./src/Lapack/Scr/dlaset.d \
./src/Lapack/Scr/dlasq1.d \
./src/Lapack/Scr/dlasq2.d \
./src/Lapack/Scr/dlasq3.d \
./src/Lapack/Scr/dlasq4.d \
./src/Lapack/Scr/dlasq5.d \
./src/Lapack/Scr/dlasq6.d \
./src/Lapack/Scr/dlasr.d \
./src/Lapack/Scr/dlasrt.d \
./src/Lapack/Scr/dlassq.d \
./src/Lapack/Scr/dlasv2.d \
./src/Lapack/Scr/dlaswp.d \
./src/Lapack/Scr/dlasy2.d \
./src/Lapack/Scr/dorg2r.d \
./src/Lapack/Scr/dorgbr.d \
./src/Lapack/Scr/dorghr.d \
./src/Lapack/Scr/dorgl2.d \
./src/Lapack/Scr/dorglq.d \
./src/Lapack/Scr/dorgqr.d \
./src/Lapack/Scr/dorm2r.d \
./src/Lapack/Scr/dormbr.d \
./src/Lapack/Scr/dormhr.d \
./src/Lapack/Scr/dorml2.d \
./src/Lapack/Scr/dormlq.d \
./src/Lapack/Scr/dormqr.d \
./src/Lapack/Scr/dtrevc.d \
./src/Lapack/Scr/dtrexc.d \
./src/Lapack/Scr/ieeeck.d \
./src/Lapack/Scr/iladlc.d \
./src/Lapack/Scr/iladlr.d \
./src/Lapack/Scr/ilaenv.d \
./src/Lapack/Scr/ilaslc.d \
./src/Lapack/Scr/ilaslr.d \
./src/Lapack/Scr/iparmq.d \
./src/Lapack/Scr/sgebak.d \
./src/Lapack/Scr/sgebal.d \
./src/Lapack/Scr/sgeev.d \
./src/Lapack/Scr/sgehd2.d \
./src/Lapack/Scr/sgehrd.d \
./src/Lapack/Scr/sgeqr2.d \
./src/Lapack/Scr/sgetf2.d \
./src/Lapack/Scr/sgetrf.d \
./src/Lapack/Scr/shseqr.d \
./src/Lapack/Scr/sisnan.d \
./src/Lapack/Scr/slabad.d \
./src/Lapack/Scr/slacpy.d \
./src/Lapack/Scr/sladiv.d \
./src/Lapack/Scr/slaexc.d \
./src/Lapack/Scr/slahqr.d \
./src/Lapack/Scr/slahr2.d \
./src/Lapack/Scr/slaisnan.d \
./src/Lapack/Scr/slaln2.d \
./src/Lapack/Scr/slange.d \
./src/Lapack/Scr/slanv2.d \
./src/Lapack/Scr/slapy2.d \
./src/Lapack/Scr/slaqr0.d \
./src/Lapack/Scr/slaqr1.d \
./src/Lapack/Scr/slaqr2.d \
./src/Lapack/Scr/slaqr3.d \
./src/Lapack/Scr/slaqr4.d \
./src/Lapack/Scr/slaqr5.d \
./src/Lapack/Scr/slarf.d \
./src/Lapack/Scr/slarfb.d \
./src/Lapack/Scr/slarfg.d \
./src/Lapack/Scr/slarfp.d \
./src/Lapack/Scr/slarft.d \
./src/Lapack/Scr/slarfx.d \
./src/Lapack/Scr/slartg.d \
./src/Lapack/Scr/slascl.d \
./src/Lapack/Scr/slaset.d \
./src/Lapack/Scr/slassq.d \
./src/Lapack/Scr/slaswp.d \
./src/Lapack/Scr/slasy2.d \
./src/Lapack/Scr/sorg2r.d \
./src/Lapack/Scr/sorghr.d \
./src/Lapack/Scr/sorgqr.d \
./src/Lapack/Scr/sorm2r.d \
./src/Lapack/Scr/sormhr.d \
./src/Lapack/Scr/sormqr.d \
./src/Lapack/Scr/strevc.d \
./src/Lapack/Scr/strexc.d 


# Each subdirectory must supply rules for building sources it contributes
src/Lapack/Scr/%.o: ../src/Lapack/Scr/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


